### ISSUE TITLE
It seems that the URL of imagenet is out of data. 

### ISSUE THREAD

**Issue by yuxinWen** [Element-Research/dataload#15]
It seems that the URL of imagenet is out of data.

**Comment by ywelement** [comment]
@yuxinWen , could you specify which URL/script you're referring to? Just tested the link (http://image-net.org/challenges/LSVRC/2014/download-images-5jj5.php) and it looks fine.

**Comment by yuxinWen** [comment]
@ywelement I mean the URL in scripts/downloadimagenet.lua. The trainURL, validURL and testURL are not valid.

**Comment by ywpre** [comment]
@yuxinWen, looks like the links to the ImageNet data sets have been changed. Thanks for spotting that. Just fixed the default URLs and it should work fine now.

**Comment by ywpre** [comment]
I'm closing this ticket since the download script has been fixed.

**Comment by yuxinWen** [comment]
@ywelement Thanks for your work.
